apiVersion: extensions/v1beta1
kind: Ingress # Type ingress
metadata:
  name: go-demo-2
  annotations: # Different configuration for the ingress what type (here we choose nginx) we can configure rate limiting and stuff like that here
    kubernetes.io/ingress.class: "nginx"
    #nginx.ingress.kubernetes.io/app-root: /app1 This can be used to add a new prefix to the app if needed (this will return 302 add /app1 as a prefix)
    ingress.kubernetes.io/ssl-redirect: "false"
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
spec: # The rules followed by the ingress to forward requests to the right service 
  rules:
  - http: 
      paths:
      - path: /demo # Any requests with prefix /demo will be forwarded to the service with name go-demo-2-api on port 8080
        backend:
          serviceName: go-demo-2-api
          servicePort: 8080