apiVersion: v1
kind: LimitRange # Type limit range to specify the min and max allowed resource allocations
metadata:
  name: limit-range
spec:
  limits:
  - default: # The default limit for a given container in a pod if not defined 
      memory: 50Mi
      cpu: 0.2
    defaultRequest: # The default request for a given container in a pod if not defined 
      memory: 30Mi
      cpu: 0.05
    max: # The max allowed values for the limit per container 
      memory: 80Mi
      cpu: 0.5
    min: # The minium allowed values for the requests per container
      memory: 10Mi
      cpu: 0.01
    type: Container