apiVersion: v1
kind: Pod # Type of the object is pod 
metadata:
  name: go-demo-2
  labels:
    type: stack 
spec:  # This is a multi container pod which is in most cases is ILL ADVISED a common pattern is having a single container per pod, except for CI/CD
  containers:  # An array of the containers running in this pod each must have a name  and the image used for the container  
  - name: db 
    image: mongo:3.3
  - name: api
    image: vfarcic/go-demo-2
    env:   # used to define the env variables passed to this container 
    - name: DB
      value: localhost
    livenessProbe:  # Method used to perform health check on the container, if it fails k8 will kill the container and apply the restart policy (which is always by default)
      httpGet:
        path: /this/path/does/not/exist
        port: 8080
      initialDelaySeconds: 5 # The initial delay for the first live probe check (to give the app some time to start)
      timeoutSeconds: 2 # Defaults to 1, The maximum time the container has time to reply else it will apply the restart policy
      periodSeconds: 5 # Defaults to 10, The interval betweeen each live prob check
      failureThreshold: 1 # Defaults to 3, The amount of times k8 should retry the live probe before considering killing the container