apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkins
spec:
  ...
  template:
    ...
    spec:
      containers:
      - name: jenkins
        image: vfarcic/jenkins
        env:
        - name: JENKINS_OPTS
          value: --prefix=/jenkins
        volumeMounts:
        - name: jenkins-home
          mountPath: /var/jenkins_home
        - name: jenkins-creds # The name of the secrets volume
          mountPath: /etc/secrets
      volumes:
      - name: jenkins-home
        emptyDir: {}
      - name: jenkins-creds  # Creating a secret volume name jenkins-cred
        secret: 
          secretName: my-creds # The name of our secret object that we created 
          defaultMode: 0444 # The mode of the created files from the secrets (read for all groups)
          items:
          - key: username # The name of the key in our secret object
            path: jenkins-user # The file that will be created from the above key
          - key: password
            path: jenkins-pass
...